package osbot_scripts.framework;

public enum AccountStage {
	TUT_ISLAND,
	QUEST_COOK_ASSISTANT,
	QUEST_ROMEO_AND_JULIET,
	QUEST_SHEEP_SHEARER,
	MINING_LEVEL_TO_15,
	MINING_IRON_ORE,
	MULE_TRADING,
	QUEST_DORICS_QUEST,
	RIMMINGTON_IRON_ORE,
	GE_SELL_BUY_MINING,
	UNKNOWN,
}
